Первая версия ДЗ2
satansdeer/loftschool-homeworks pull request #34
Opened 2019-04-09 08:30 UTC by alant79

2019-04-09 17:27 UTC, taksenov requested changes

2019-04-09 17:27 UTC, taksenov commented on src/components/Chat/Chat.js
> +        this.setState({messageInput: e.target.value})
Давай начнем использовать деструктуризацию

2019-04-09 17:27 UTC, taksenov commented on src/components/Chat/Chat.js
> +
вот такие отвисшие скобки не комильфо. Преттир не настроен в IDE?

2019-04-09 17:27 UTC, taksenov commented on src/components/Chat/Chat.js
> +                messages: [...prevState.messages, {text: this.state.messageInput}],
Деструктуризация

2019-04-09 17:27 UTC, taksenov commented on src/components/Chat/Chat.js
> +            this.setState((prevState => ({
Проверки на пустой ввод нет

2019-04-09 17:27 UTC, taksenov commented on src/components/Chat/Chat.js
> +                    {this.state.messages.map((message,index) => (
Тоже деструктуризация

2019-04-09 17:27 UTC, taksenov commented on src/components/Chat/Chat.js
> +
Отвисшая скобка ;(

2019-04-10 17:13 UTC, KustovAA commented on src/components/Chat/Chat.js
> +            {messages.map((message, index) => (
деструктурируй message в { text } в messages.map

2019-04-10 17:13 UTC, KustovAA commented on src/components/Message/Message.js
>  class Message extends React.Component {
Лучше переделай на функцию, так как state и lifecycle методы тут не используются. В одну строчку может поместиться.
и не забудь деструктуризацию)

2019-04-10 17:19 UTC, taksenov commented on src/components/Chat/Chat.js
> +            {messages.map((message, index) => (
```js
{messages.map((message, index) => {
  const { text } = message;

  return (<Message text={text} key={`${text}+${index}`} />)
})}
```

должно выглядеть примерно вот так. Попробуй прогнать такой код, если не получится то напиши. Я сейчас просто без проверки написал, может быть где-то ошибся со скобками.

2019-04-10 17:24 UTC, KustovAA commented on src/components/Message/Message.js
>  class Message extends React.Component {
что-то вроде этого - сonst Message = ({ text }) => <span>{text}</span>

2019-04-19 12:56 UTC, closed without merging