Done hw 2
satansdeer/loftschool-homeworks pull request #67
Opened 2019-04-11 23:03 UTC by Theodikes

2019-04-12 06:44 UTC, klepnevEA commented
Commit

2019-04-14 09:23 UTC, taksenov requested changes

2019-04-14 09:23 UTC, taksenov commented on src/components/Chat/index.js
> +        messages: this.state.messages.concat({ text: this.state.messageInput }),
`messages: [...messages, { text: messageInput }]`

2019-04-14 09:23 UTC, taksenov commented on src/components/Chat/index.js
> +  sendMessageOnEnter(e) {
```js
  sendMessageOnEnter = event => {
    const { messageInput, messages } = this.state;
```

2019-04-14 09:23 UTC, taksenov commented on src/components/Chat/index.js
> +  render() {
```js
  render() {
    const { messageInput, messages } = this.state;
    ...
    <input
          className="input-message"
          onChange={this.changeInputMessage}
          onKeyPress={this.sendMessageOnEnter}
          value={messageInput}
        />
```

2021-11-03 06:01 UTC, closed without merging