HW#2 Platova
satansdeer/loftschool-homeworks pull request #70
Opened 2019-04-12 18:29 UTC by kplatova

Ломаются 2 теста: 

1. - Компонента Chat › проверка рендера компонент Messages › Содержимое state.messages рендерится в список компонент Message
2. - Компонента Chat › Поведение компоненты › При нажатии Enter в input, значение в state.messages станет содержать [{text: значение_из_messageInput}], а state.messageInput станет пустой строкой ""

Я уже всю голову сломала, почему так. Могли бы объяснить?

2019-04-13 10:07 UTC, rchesnokov requested changes

2019-04-13 10:07 UTC, rchesnokov commented on src/components/Chat/Chat.js
> +          onChange={({ target: { value } }) => this.changeInputMessage(value)}
Лучше все таки деструктуризацию делать уже в самом методе чтобы не перегружать шаблон (тяжелее читается)

2019-04-13 10:07 UTC, rchesnokov commented on src/components/Chat/Chat.js
> +      document.querySelector('.messages').scrollIntoView({
1) Вся проблема с тестами из-за этой функции. Вкратце, при использовании поверхностного рендеринга у нас нет прямого доступа к ДОМ-элементам. Чтобы починить тест, нужно его немного подправить, сейчас не будем вдаваться в подробности что именно там происходит, тема тестирования будет на 4 неделе обучения.

Вот код который нужно заменить в `Chat.test.js`: https://pastebin.com/eHPWU8pU 

2) Когда нам нужен доступ из React к какому-то дом-элементу мы используем `refs`. Почитать про них можно в документации: https://reactjs.org/docs/refs-and-the-dom.html

3) Сейчас если вбить много сообщений, то можно увидеть, что контейнер `.messages` скроллится всегда не до конца (1 сообщение постоянно остается скрытым внизу). Подумай, пожалуйста, почему так происходит, и как это исправить. (Подсказка: в каком порядке отрабатывают методы `sendMessageOnEnter` и `render`? Какой lifecycle метод может тут помочь?)

2019-04-13 20:20 UTC, kplatova commented on src/components/Chat/Chat.js
> +      document.querySelector('.messages').scrollIntoView({
1. Done
2. Done
3. Сначала `render()`, потом `sendMessageOnEnter`. И соответсвенно нужно вставлять саму ф-ю скролла в метод `componentDidUpdate`, тк компонент уже примонтировался и в данный момент у нас есть возможность использовать refs, а следовательно это то самое место, где мы хотели бы сделать скролл до конца контейнера. Верно?

2019-04-14 05:25 UTC, rchesnokov commented on src/components/Chat/Chat.js
> +      document.querySelector('.messages').scrollIntoView({
3. Верно.

2019-04-14 05:25 UTC, rchesnokov approved these changes
Принято.

2021-11-03 06:01 UTC, closed without merging